import React,{useEffect,useRef,useState} from 'react';
import {ActivityIndicator,AppState,Image,KeyboardAvoidingView,Linking,Modal,Platform,Pressable,ScrollView,Text,TextInput,View} from 'react-native';
import {SafeAreaProvider,SafeAreaView} from 'react-native-safe-area-context';
import {StatusBar} from 'expo-status-bar';
import * as ImagePicker from 'expo-image-picker';
import * as DocumentPicker from 'expo-document-picker';
import * as Clipboard from 'expo-clipboard';
import * as FS from 'expo-file-system/legacy';
import * as Notifications from 'expo-notifications';
import Constants from 'expo-constants';
import {CATEGORIES,EMPTY,dateFields,id,inferNotice,parseDate,updateNotice,validateBackup,type Category,type Notice,type State} from './domain';
import * as api from './services';
import {Button,Chips,Field,Icon,confirm,notify,p,s} from './ui';
import {privacy} from './privacy';
type Tab='today'|'all'|'add'|'family'|'settings';
type Draft={title:string;source:string;image?:string;category:Category;date:string;time:string;assignee:string;checks:string;remind:number|null;editing?:string};
const blank=():Draft=>({title:'',source:'',category:'生活',date:'',time:'',assignee:'我',checks:'',remind:60});
const fmt=(d:string|null)=>d?new Date(d).toLocaleString('zh-TW',{month:'numeric',day:'numeric',weekday:'short',hour:'2-digit',minute:'2-digit'}):'日期待確認';
export default function App(){return <SafeAreaProvider><Main/></SafeAreaProvider>}
function Main(){
 const [data,setData]=useState<State>(EMPTY),[ready,setReady]=useState(false),[loadError,setLoadError]=useState('');const live=useRef(data);
 const [tab,setTab]=useState<Tab>('today'),[draft,setDraft]=useState<Draft>(blank),[warnings,setWarnings]=useState<string[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [selected,setSelected]=useState<string|null>(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('未完成'),[member,setMember]=useState(''),[policy,setPolicy]=useState(false),[notificationStatus,setNotificationStatus]=useState('提醒只會在授權後送達。');
 const lock=useRef(false),scroll=useRef<ScrollView>(null);const notice=data.notices.find(n=>n.id===selected);
 const reload=async()=>{try{const d=await api.load();live.current=d;setData(d);setLoadError('');setReady(true);api.syncReminders(d.notices).then(setNotificationStatus).catch(()=>setNotificationStatus('提醒排程失敗，請到設定重試。'));}catch{setLoadError('本機資料無法讀取。為避免覆蓋原資料，目前停止寫入，請先重新載入。');}};
 useEffect(()=>{void reload();const app=AppState.addEventListener('change',state=>{if(state==='active')api.syncReminders(live.current.notices).then(setNotificationStatus).catch(()=>setNotificationStatus('提醒排程失敗，請到設定重試。'))});let response:ReturnType<typeof Notifications.addNotificationResponseReceivedListener>|undefined;if(Platform.OS!=='web'){response=Notifications.addNotificationResponseReceivedListener(r=>{const n=r.notification.request.content.data?.noticeId;if(typeof n==='string')setSelected(n)});Notifications.getLastNotificationResponseAsync().then(r=>{const n=r?.notification.request.content.data?.noticeId;if(typeof n==='string')setSelected(n)}).catch(()=>{});}return()=>{app.remove();response?.remove();}},[]);
 useEffect(()=>{scroll.current?.scrollTo({y:0,animated:false})},[tab]);
 const run=async(job:()=>Promise<void>)=>{if(lock.current)return;lock.current=true;setBusy(true);try{await job()}catch(e){notify(e instanceof Error?e.message:'操作失敗，請稍後重試。')}finally{lock.current=false;setBusy(false)}};
 const commit=async(next:State,permission=false)=>{await api.persist(next);live.current=next;setData(next);try{setNotificationStatus(await api.syncReminders(next.notices,permission))}catch{setNotificationStatus('資料已保存，但提醒未排程成功。請到設定重試。')}};
 const patchDraft=(patch:Partial<Draft>)=>setDraft(d=>({...d,...patch}));
 const startNew=async()=>{if((draft.title||draft.source||draft.image)&&!(await confirm('放棄尚未儲存的草稿，新增另一則通知？')))return;setDraft(blank());setWarnings([]);setMessage('');setTab('add')};
 const parse=()=>{if(!draft.source.trim()){notify('請先貼上通知文字，或選擇截圖。');return;}const r=inferNotice(draft.source);setDraft(d=>({...d,title:r.title,category:r.category,date:r.date,time:r.time,checks:r.checklist.join('\n')}));setWarnings(r.warnings);setMessage('整理完成。請確認標題、日期與準備事項再儲存。')};
 const pickImage=()=>run(async()=>{const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:1});if(r.canceled)return;const uri=r.assets[0].uri;patchDraft({image:uri});try{const text=await api.recognize(uri);if(!text.trim())throw new Error('沒有辨識到文字，請換一張清晰截圖或直接貼上文字。');patchDraft({source:text.slice(0,20000)});setMessage('已辨識文字，請點「整理成事項」並校對。')}catch(e){setMessage(e instanceof Error?e.message:'辨識失敗，請貼上文字。')}});
 const edit=(n:Notice,source?:string)=>{setSelected(null);setDraft({title:n.title,source:source??n.source,image:n.sourceImage,category:n.category,...dateFields(n.dueAt),assignee:n.assignee,checks:n.checklist.map(c=>c.text).join('\n'),remind:n.remindMinutes,editing:n.id});setWarnings([]);setMessage(source?'已載入原事項；確認更正內容後儲存，原紀錄會保留。':'編輯後儲存，提醒時間將一併更新。');setTab('add')};
 const save=()=>run(async()=>{
  if(!draft.title.trim())throw new Error('請填寫事項標題。');if(live.current.notices.length>=2000&&!draft.editing)throw new Error('最多保存2000則事項，請先備份並刪除不需要的資料。');
  const dueAt=parseDate(draft.date,draft.time);if(dueAt&&Date.parse(dueAt)<Date.now()&&!(await confirm('日期已經過去，仍要儲存？不會補發過期提醒。')))return;
  const old=live.current.notices.find(n=>n.id===draft.editing);if(!old&&draft.source.trim()&&live.current.notices.some(n=>n.source.trim()===draft.source.trim()))throw new Error('這段通知已存在。請在下方選擇原事項進行更正，避免重複提醒。');
  const lines=draft.checks.split('\n').map(x=>x.trim()).filter(Boolean);if(lines.length>50||lines.some(x=>x.length>200))throw new Error('準備清單最多50項，每項最多200字。');
  let image=draft.image;if(image&&image!==old?.sourceImage)image=await api.keepImage(image);const at=new Date().toISOString();
  const patch={title:draft.title.trim(),source:draft.source.trim(),sourceImage:image,category:draft.category,dueAt,assignee:live.current.members.includes(draft.assignee)?draft.assignee:'我',checklist:lines.map(text=>old?.checklist.find(c=>c.text===text)??{id:id(),text,done:false}),remindMinutes:dueAt?draft.remind:null};
  const item:Notice=old?updateNotice(old,patch):{...patch,id:id(),done:false,createdAt:at,updatedAt:at,history:[]};
  await commit({...live.current,notices:old?live.current.notices.map(n=>n.id===old.id?item:n):[item,...live.current.notices]},item.remindMinutes!==null);
  if(old?.sourceImage&&old.sourceImage!==image)await api.removeImage(old.sourceImage).catch(()=>{});setDraft(blank());setWarnings([]);setMessage('');setTab('today');setSelected(item.id);
 });
 const toggle=(n:Notice)=>run(async()=>{await commit({...live.current,notices:live.current.notices.map(x=>x.id===n.id?updateNotice(x,{done:!x.done}):x)})});
 const remove=(n:Notice)=>run(async()=>{if(!(await confirm('刪除這則事項、修改紀錄與原始附件？此操作無法復原。')))return;await commit({...live.current,notices:live.current.notices.filter(x=>x.id!==n.id)});setSelected(null);await api.removeImage(n.sourceImage)});
 const restore=()=>run(async()=>{const r=await DocumentPicker.getDocumentAsync({type:['application/json','text/plain'],copyToCacheDirectory:true});if(r.canceled)return;const a=r.assets[0];if(a.size&&a.size>10_000_000)throw new Error('備份檔過大，上限10MB。');const text=Platform.OS==='web'?await a.file!.text():await FS.readAsStringAsync(a.uri);if(text.length>10_000_000)throw new Error('備份檔過大。');const next=validateBackup(JSON.parse(text));if(!(await confirm(`以 ${next.notices.length} 則事項取代目前全部資料？備份不含圖片，建議先匯出目前資料。`)))return;await commit(next);if(Platform.OS!=='web')await FS.deleteAsync(FS.documentDirectory+'sources/',{idempotent:true});setSelected(null);setDraft(blank());notify('文字資料已還原。附件圖片不包含在備份中。')});
 const pending=data.notices.filter(n=>!n.done),end=new Date();end.setHours(23,59,59,999);
 const order=(a:Notice,b:Notice)=>(a.dueAt?Date.parse(a.dueAt):Infinity)-(b.dueAt?Date.parse(b.dueAt):Infinity);
 const today=pending.filter(n=>n.dueAt&&Date.parse(n.dueAt)<=end.getTime()).sort(order),upcoming=pending.filter(n=>n.dueAt&&Date.parse(n.dueAt)>end.getTime()).sort(order).slice(0,3),undated=pending.filter(n=>!n.dueAt);
 const filtered=data.notices.filter(n=>(filter==='全部'||filter==='已完成'&&n.done||filter==='未完成'&&!n.done)&&`${n.title} ${n.source} ${n.assignee}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Number(a.done)-Number(b.done)||order(a,b));
 const card=(n:Notice)=><Pressable key={n.id} accessibilityRole="button" accessibilityLabel={`查看 ${n.title}`} onPress={()=>setSelected(n.id)} style={s.card}><View style={s.row}><View style={s.categoryDot}><Icon name={n.done?'checkmark':n.category==='取件'?'cube-outline':n.category==='帳單'?'receipt-outline':n.category==='學校'?'school-outline':'calendar-outline'} size={20}/></View><View style={s.flex}><Text style={s.caption}>{n.category}{n.history.length?' · 已更正':''}</Text><Text style={[s.cardTitle,n.done&&{textDecorationLine:'line-through',color:p.muted}]}>{n.title}</Text><Text style={[s.caption,!n.done&&n.dueAt&&Date.parse(n.dueAt)<Date.now()?{color:p.red}:{}]}>{fmt(n.dueAt)}</Text></View><Icon name="chevron-forward" size={17} color={p.muted}/></View><View style={s.cardFoot}><Text style={s.caption}>{n.assignee}負責</Text><Text style={s.caption}>{n.checklist.length?`準備 ${n.checklist.filter(c=>c.done).length}/${n.checklist.length}`:'無準備事項'}</Text></View></Pressable>;
 const empty=(title:string,body:string)=><View style={s.empty}><Icon name="leaf-outline" size={38}/><Text style={s.emptyTitle}>{title}</Text><Text style={s.body}>{body}</Text></View>;
 if(loadError)return <SafeAreaView style={s.root}><View style={s.content}><Text style={s.heading}>資料讀取需要協助</Text><Text style={s.body}>{loadError}</Text><Button label="重新載入" onPress={()=>void reload()}/></View></SafeAreaView>;
 if(!ready)return <SafeAreaView style={s.root}><ActivityIndicator accessibilityLabel="正在讀取事項" style={{marginTop:100}} color={p.green}/></SafeAreaView>;
 return <SafeAreaView style={s.root} edges={['top','left','right']}><StatusBar style="dark"/><View style={s.top}><View style={s.row}><View style={s.logo}><Icon name="notifications-outline" color="white" size={21}/></View><Text style={s.brand}>生活通知管家</Text></View><Text style={s.local}>本機保存</Text></View><KeyboardAvoidingView style={s.flex} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView ref={scroll} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
 {tab==='today'&&<><Text style={s.eyebrow}>{new Date().toLocaleDateString('zh-TW',{month:'long',day:'numeric',weekday:'long'})}</Text><Text style={s.heading}>把重要的事，<Text style={{color:p.green}}>放心記下。</Text></Text><View style={s.summary}><View><Text style={s.summaryNum}>{today.length}</Text><Text style={s.caption}>今天與待處理</Text></View><View style={s.divider}/><View><Text style={s.summaryNum}>{undated.length}</Text><Text style={s.caption}>日期待確認</Text></View><Pressable accessibilityRole="button" accessibilityLabel="新增通知" onPress={()=>void startNew()} style={s.addRound}><Icon name="add" color="white" size={28}/></Pressable></View>{notificationStatus.startsWith('提醒尚未')&&pending.some(n=>n.remindMinutes!==null)&&<Text style={s.warning}>{notificationStatus}</Text>}<Text style={s.sectionTitle}>先處理這些</Text>{today.length?today.map(card):empty('今天沒有到期事項','新增通知後，截止日與準備清單會出現在這裡。')}{upcoming.length>0&&<><Text style={s.sectionTitle}>接下來</Text>{upcoming.map(card)}</>}{undated.length>0&&<><Text style={s.sectionTitle}>補上日期更安心</Text>{undated.slice(0,3).map(card)}</>}<Button label="新增一則通知" onPress={()=>void startNew()}/></>}
 {tab==='all'&&<><Text style={s.eyebrow}>通知收件匣</Text><Text style={s.heading}>每件事，都找得到。</Text><TextInput accessibilityLabel="搜尋事項或原始通知" style={s.input} placeholder="搜尋事項、原文或負責人" value={query} onChangeText={setQuery}/><Chips values={['未完成','已完成','全部'].map(x=>[x,x])} value={filter} onChange={setFilter}/>{filtered.map(card)}{!filtered.length&&empty('沒有符合的事項','換個關鍵字，或新增第一則通知。')}</>}
 {tab==='add'&&<><Text style={s.eyebrow}>{draft.editing?'更新既有通知':'截圖或貼上文字'}</Text><Text style={s.heading}>{draft.editing?'更正一次，放心接續。':'讓通知變成下一步。'}</Text><View style={s.row}><View style={s.flex}><Button label="選擇截圖" secondary disabled={busy} onPress={pickImage}/></View><View style={s.flex}><Button label="貼上文字" secondary onPress={()=>void run(async()=>patchDraft({source:(await Clipboard.getStringAsync()).slice(0,20000)}))}/></View></View>{draft.image&&<><Image accessibilityLabel="原始通知截圖" source={{uri:draft.image}} style={s.sourcePreview} resizeMode="contain"/><Button label="移除這張附件" secondary onPress={()=>patchDraft({image:undefined})}/></>}<Field label="原始通知" value={draft.source} onChange={source=>patchDraft({source})} multiline placeholder="貼上學校通知、繳費說明、取件或活動訊息…"/><Button label="整理成事項" secondary onPress={parse}/>{message?<Text accessibilityLiveRegion="polite" style={s.info}>{message}</Text>:null}{warnings.map(w=><Text key={w} style={s.warning}>{w}</Text>)}<Field label="事項標題" value={draft.title} max={100} onChange={title=>patchDraft({title})} placeholder="例如：回覆校外教學意願"/><Text style={s.label}>分類</Text><Chips values={CATEGORIES.map(c=>[c,c])} value={draft.category} onChange={category=>patchDraft({category})}/><View style={s.row}><View style={{flex:1.4}}><Field label="截止日期" value={draft.date} max={10} onChange={date=>patchDraft({date})} placeholder="YYYY-MM-DD"/></View><View style={s.flex}><Field label="截止時間" value={draft.time} max={5} onChange={time=>patchDraft({time})} placeholder="HH:mm"/></View></View><Text style={s.caption}>使用目前手機時區。兩欄留白可先存為日期待確認。</Text><Text style={s.label}>提醒</Text><Chips<number|null> values={[[null,'不提醒'],[0,'準時'],[60,'1小時前'],[1440,'1天前']]} value={draft.remind} onChange={remind=>patchDraft({remind})}/><Text style={s.label}>誰來負責</Text><Chips values={data.members.map(m=>[m,m])} value={draft.assignee} onChange={assignee=>patchDraft({assignee})}/><Field label="準備清單（每行一項）" value={draft.checks} onChange={checks=>patchDraft({checks})} multiline placeholder={'確認參加人數\n準備水壺\n回覆老師'}/><Button label={draft.editing?'儲存更正':'確認並儲存'} disabled={busy} onPress={save}/>{(draft.title||draft.source)&&<Button label="清除草稿" secondary onPress={()=>void startNew()}/>}{!draft.editing&&draft.source.trim()&&data.notices.filter(n=>n.source.trim()===draft.source.trim()||draft.title.length>2&&n.title.includes(draft.title)).slice(0,3).map(n=><View style={s.card} key={n.id}><Text style={s.label}>可能是同一則通知：{n.title}</Text><Button label="改為更正這則事項" secondary onPress={()=>edit(n,draft.source)}/></View>)}<Text style={s.caption}>整理依據本機文字規則，不會推測未寫明的期限。請核對原文。</Text></>}
 {tab==='family'&&<><Text style={s.eyebrow}>一起分工</Text><Text style={s.heading}>誰來處理，一眼清楚。</Text><Text style={s.body}>在這台手機標記負責人，再把事項分享給家人。分享的是文字副本，沒有帳號或跨手機即時同步。</Text>{data.members.map(m=><View style={s.card} key={m}><View style={s.row}><Icon name="person-circle-outline" size={36}/><View style={s.flex}><Text style={s.cardTitle}>{m}</Text><Text style={s.caption}>{pending.filter(n=>n.assignee===m).length} 件未完成</Text></View>{m!=='我'&&<Pressable accessibilityRole="button" accessibilityLabel={`移除成員 ${m}`} onPress={()=>void run(async()=>{if(await confirm(`移除「${m}」？相關事項改由「我」負責。`))await commit({...live.current,members:live.current.members.filter(x=>x!==m),notices:live.current.notices.map(n=>n.assignee===m?updateNotice(n,{assignee:'我'}):n)})})}><Icon name="close-circle-outline" color={p.muted}/></Pressable>}</View>{pending.filter(n=>n.assignee===m).slice(0,3).map(n=><Pressable key={n.id} accessibilityRole="button" onPress={()=>setSelected(n.id)} style={s.memberTask}><Text style={s.body}>{n.title}</Text><Text style={s.caption}>{fmt(n.dueAt)}</Text></Pressable>)}</View>)}<Field label="新增負責人" value={member} onChange={setMember} max={30} placeholder="例如：媽媽、爸爸、室友"/><Button label="新增成員" onPress={()=>void run(async()=>{const m=member.trim();if(!m)throw new Error('請填寫名字。');if(live.current.members.includes(m))throw new Error('這個成員已經存在。');if(live.current.members.length>=20)throw new Error('最多20位成員。');await commit({...live.current,members:[...live.current.members,m]});setMember('')})}/></>}
 {tab==='settings'&&<><Text style={s.eyebrow}>你的資料，你決定</Text><Text style={s.heading}>設定與資料管理</Text><View style={s.card}><Text style={s.sectionTitle}>提醒設定</Text><Text style={s.body}>{notificationStatus}</Text><Text style={s.caption}>最多排程最近40筆未來提醒，開啟 App 時補排。手机勿擾、權限與省電設定可能影響送達；此工具不適合作為緊急警報。</Text><Button label="允許通知並重新排程" secondary onPress={()=>void run(async()=>setNotificationStatus(await api.syncReminders(live.current.notices,true)))}/><Button label="10秒後測試提醒" secondary onPress={()=>void run(async()=>{await api.testReminder();notify('已安排10秒後測試提醒。請切換至背景確認。')})}/>{Platform.OS!=='web'&&<Button label="開啟系統設定" secondary onPress={()=>void Linking.openSettings()}/>}</View><View style={s.card}><Text style={s.sectionTitle}>備份與還原</Text><Text style={s.body}>匯出事項、原文、準備清單與更正紀錄。備份不包含截圖附件；檔案含私人資料，請妥善保存。</Text><Button label="匯出文字備份" secondary onPress={()=>void run(()=>api.exportBackup(live.current))}/><Button label="從備份還原" secondary onPress={restore}/></View><View style={s.card}><Text style={s.sectionTitle}>隱私與支援</Text><Text style={s.body}>通知原文與截圖留在本機，無廣告追蹤、無雲端帳號。不會讀取其他 App 的通知或私人群組。</Text><Button label="隱私權政策與使用說明" secondary onPress={()=>setPolicy(true)}/>{Constants.expoConfig?.extra?.supportEmail&&<Button label="聯絡支援" secondary onPress={()=>void Linking.openURL('mailto:'+Constants.expoConfig!.extra!.supportEmail)}/>}<Text style={s.caption}>版本 1.0.0 · 請以原始通知為準。</Text></View><Button label="刪除這台裝置的全部資料" danger onPress={()=>void run(async()=>{if(await confirm('永久刪除全部事項、成員、原圖與提醒？已匯出的備份不會一併刪除。')){await api.erase();const next={...EMPTY,members:['我'],notices:[]};live.current=next;setData(next);setDraft(blank());setSelected(null);setTab('today')}})}/></>}
 </ScrollView></KeyboardAvoidingView><SafeAreaView edges={['bottom']} style={s.bottom}><View style={s.tabs}>{([['today','今天','sunny-outline'],['all','全部','file-tray-full-outline'],['add','新增','add-circle-outline'],['family','分工','people-outline'],['settings','設定','settings-outline']] as const).map(([key,label,icon])=><Pressable key={key} accessibilityRole="tab" accessibilityLabel={label} accessibilityState={{selected:tab===key}} onPress={()=>setTab(key)} style={s.tab}><Icon name={icon} color={tab===key?p.green:p.muted} size={24}/><Text style={[s.tabText,tab===key&&{color:p.green,fontWeight:'700'}]}>{label}</Text></Pressable>)}</View></SafeAreaView>
 <Modal visible={!!notice} onRequestClose={()=>setSelected(null)} animationType="slide"><SafeAreaView style={s.root}><View style={s.modalBar}><Text style={s.label}>事項詳情</Text><Button label="關閉" secondary onPress={()=>setSelected(null)}/></View>{notice&&<ScrollView contentContainerStyle={s.content}><Text style={s.eyebrow}>{notice.category} · {notice.assignee}負責</Text><Text style={s.heading}>{notice.title}</Text><Text style={s.detailDate}>{fmt(notice.dueAt)}</Text><Text style={s.caption}>{notice.remindMinutes===null?'此事項未開啟提醒':notice.remindMinutes===0?'截止時提醒':`提前 ${notice.remindMinutes/60} 小時提醒`}</Text><Text style={s.info}>{notificationStatus}</Text><Text style={s.sectionTitle}>準備清單</Text>{notice.checklist.length===0?<Text style={s.caption}>還沒有準備事項，可在編輯中新增。</Text>:notice.checklist.map(c=><Pressable key={c.id} accessibilityLabel={c.text} accessibilityRole="checkbox" accessibilityState={{checked:c.done}} onPress={()=>void run(async()=>{await commit({...live.current,notices:live.current.notices.map(n=>n.id===notice.id?updateNotice(n,{checklist:n.checklist.map(x=>x.id===c.id?{...x,done:!x.done}:x)}):n)})})} style={s.checkRow}><Icon name={c.done?'checkbox':'square-outline'}/><Text style={[s.body,s.flex,c.done&&{textDecorationLine:'line-through',color:p.muted}]}>{c.text}</Text></Pressable>)}<Button label={notice.done?'重新開啟事項':'標記已完成'} onPress={()=>toggle(notice)}/><View style={s.row}><View style={s.flex}><Button label="編輯／更正" secondary onPress={()=>edit(notice)}/></View><View style={s.flex}><Button label="分享給家人" secondary onPress={()=>void run(()=>api.shareNotice(notice))}/></View></View>{notice.dueAt&&<Button label="匯出到行事曆" secondary onPress={()=>void run(()=>api.exportCalendar(notice))}/>}<Text style={s.sectionTitle}>原始通知</Text><Text selectable style={s.sourceText}>{notice.source||'手動建立，未附原文。'}</Text>{notice.sourceImage&&<Image source={{uri:notice.sourceImage}} style={s.sourceFull} resizeMode="contain" accessibilityLabel="原始通知圖片"/>}{notice.history.length>0&&<><Text style={s.sectionTitle}>更正紀錄</Text>{notice.history.map((h,i)=><View key={h.at+i} style={s.card}><Text style={s.caption}>{new Date(h.at).toLocaleString('zh-TW')} 更正前</Text><Text style={s.cardTitle}>{h.title}</Text><Text style={s.caption}>{fmt(h.dueAt)}</Text><Text selectable style={s.body}>{h.source}</Text></View>)}</>}<Button label="刪除這則事項" danger onPress={()=>remove(notice)}/></ScrollView>}</SafeAreaView></Modal>
 <Modal visible={!data.welcomed&&!policy} animationType="fade" onRequestClose={()=>{}}><SafeAreaView style={s.root}><ScrollView contentContainerStyle={[s.content,{paddingTop:50}]}><View style={s.welcomeIcon}><Icon name="notifications-outline" size={48} color="white"/></View><Text style={s.eyebrow}>歡迎使用生活通知管家</Text><Text style={s.heading}>通知很多，<Text style={{color:p.green}}>不必全靠記憶。</Text></Text><Text style={s.body}>把截圖或文字整理成期限、準備清單和負責人。每次更正，都保留原始依據。</Text>{([['image-outline','匯入截圖與文字','由你選擇要整理的內容，不讀取其他 App。'],['checkmark-done-outline','先確認，再提醒','辨識結果需要校對，未確認的日期不會猜測。'],['lock-closed-outline','資料留在這台手機','免登入；需要換機時，先匯出文字備份。']] as const).map(([i,t,b])=><View key={t} style={s.welcomeRow}><Icon name={i}/><View style={s.flex}><Text style={s.cardTitle}>{t}</Text><Text style={s.body}>{b}</Text></View></View>)}<Button label="開始整理生活" onPress={()=>void run(()=>commit({...live.current,welcomed:true}))}/><Button label="先閱讀隱私說明" secondary onPress={()=>setPolicy(true)}/></ScrollView></SafeAreaView></Modal>
 <Modal visible={policy} onRequestClose={()=>setPolicy(false)} animationType="slide"><SafeAreaView style={s.root}><View style={s.modalBar}><Text style={s.label}>隱私與使用說明</Text><Button label="關閉" secondary onPress={()=>setPolicy(false)}/></View><ScrollView contentContainerStyle={s.content}><Text style={s.heading}>把選擇留給你。</Text><Text selectable style={s.body}>{privacy(Constants.expoConfig?.extra?.supportEmail)}</Text></ScrollView></SafeAreaView></Modal>
 {busy&&<View style={s.busy} pointerEvents="auto"><ActivityIndicator color="white"/><Text style={{color:'white'}}>正在處理…</Text></View>}
 </SafeAreaView>;
}
