import React,{useState} from 'react';
import {Pressable,StyleSheet,Text,View} from 'react-native';
import type {Notice} from './domain';
import {dayKey,displayDay,displayTime,noticesForDay} from './calendar';
import {Button,Chips,Field,Icon,p,s} from './ui';

const tones={生活:['#E4EFE9','#326753'],學校:['#EAE6F6','#65568A'],帳單:['#F9EBDD','#966034'],取件:['#E1EDF3','#426B80'],活動:['#FAE4DD','#A45741']} as const;
export function EventCard({notice:n,onOpen}:{notice:Notice;onOpen:(id:string)=>void}){
 const [soft,color]=tones[n.category];
 return <Pressable accessibilityRole="button" accessibilityLabel={`${n.title}，查看詳情`} onPress={()=>onOpen(n.id)} style={({pressed})=>[h.event,pressed&&{opacity:.7}]}>
  <View style={[h.dateBlock,{backgroundColor:soft}]}><Text style={[h.dateNumber,{color}]}>{n.dueAt?new Date(n.dueAt).getDate():'待'}</Text><Text style={[h.dateMonth,{color}]}>{n.dueAt?`${new Date(n.dueAt).getMonth()+1} 月`:'辦事項'}</Text></View>
  <View style={s.flex}><Text numberOfLines={2} style={h.eventTitle}>{n.title}</Text><Text style={s.caption}>{n.done?'已完成':n.needsReview?'需要確認':n.dueAt?n.allDay?'全天':displayTime(new Date(n.dueAt)):'無期限'}{n.location?` · ${n.location}`:` · ${n.category}`}</Text></View><Icon name="chevron-forward" size={18} color={p.muted}/>
 </Pressable>;
}
export function HomeDashboard({notices,onOpen,onToggle,onAdd,onCapture,onCalendar,onSettings,listenerEnabled,issue}:{notices:Notice[];onOpen:(id:string)=>void;onToggle:(n:Notice)=>void;onAdd:()=>void;onCapture:(type:'image'|'text')=>void;onCalendar:()=>void;onSettings:()=>void;listenerEnabled:boolean;issue:string}){
 const[filter,setFilter]=useState<'today'|'todo'|'review'|'all'>('today'),[query,setQuery]=useState(''),[limit,setLimit]=useState(12);
 const now=new Date(),pending=notices.filter(n=>!n.done),today=noticesForDay(pending,dayKey(now)),todos=pending.filter(n=>!n.dueAt&&!n.needsReview),review=pending.filter(n=>n.needsReview);
 const next=[...pending].filter(n=>n.dueAt&&!n.needsReview&&(n.allDay?dayKey(n.dueAt)>=dayKey(now):Date.parse(n.endAt||n.dueAt)>=now.getTime())).sort((a,b)=>Date.parse(a.dueAt!)-Date.parse(b.dueAt!))[0];
 const completed=notices.filter(n=>n.done&&dayKey(n.updatedAt)===dayKey(now)).length;
 const source=filter==='today'?today:filter==='todo'?todos:filter==='review'?review:pending;
 const items=source.filter(n=>!query.trim()||`${n.title} ${n.location||''} ${n.source}`.toLowerCase().includes(query.trim().toLowerCase()));
 const total=completed+today.length+todos.length;
 return <View>
  <View style={h.headingRow}><View><Text style={h.eyebrow}>{displayDay(now)}</Text><Text style={h.heading}>今天的安排</Text></View><Pressable accessibilityRole="button" accessibilityLabel="新增行程或待辦" onPress={onAdd} style={h.add}><Icon name="add" color="white" size={26}/></Pressable></View>
  <Pressable accessibilityRole="button" accessibilityLabel={next?`下一個行程：${next.title}`:'新增第一個行程'} onPress={()=>next?onOpen(next.id):onAdd()} style={h.hero}>
   <View style={h.heroTop}><Text style={h.heroLabel}>{next?'下一個行程':'近期行程'}</Text><Icon name={next?'arrow-forward-outline':'sunny-outline'} color="#EAC8A5" size={23}/></View>
   <Text numberOfLines={2} style={h.heroTitle}>{next?next.title:'尚無即將到來的行程'}</Text>
   <View style={h.heroBottom}><Text style={h.heroMeta}>{next?`${displayDay(new Date(next.dueAt!))} · ${next.allDay?'全天':displayTime(new Date(next.dueAt!))}`:'新增行程，或從截圖開始'}</Text><View style={h.heroArrow}><Icon name="arrow-forward" color="#153C34" size={19}/></View></View>
  </Pressable>
  <View style={h.quickRow}>{([['image','scan-outline','截圖辨識','#F6E5DC'],['text','clipboard-outline','貼上文字','#E9E5F5']] as const).map(([type,icon,title,color])=><Pressable accessibilityRole="button" key={type} onPress={()=>onCapture(type)} style={h.quick}><View style={[h.quickIcon,{backgroundColor:color}]}><Icon name={icon} color={p.ink} size={22}/></View><Text style={h.quickText}>{title}</Text><Icon name="add" size={17} color={p.muted}/></Pressable>)}</View>
  {total>0&&<View style={h.progressCard}><View style={s.row}><Icon name="checkmark-circle" size={20}/><Text style={[s.caption,s.flex]}>今天已完成 <Text style={{fontWeight:'700',color:p.ink}}>{completed}</Text> 件</Text><Text style={s.caption}>{total?Math.round(completed/total*100):0}%</Text></View><View style={h.track}><View style={[h.fill,{width:`${total?completed/total*100:0}%`}]}/></View></View>}
  {!!issue&&<Text accessibilityLiveRegion="polite" style={s.warning}>{issue}</Text>}
  {!listenerEnabled&&<Pressable accessibilityRole="button" onPress={onSettings} style={h.setup}><Icon name="notifications-outline" size={20}/><Text style={[s.caption,s.flex]}>選擇通知來源，自動收進重要事項</Text><Icon name="chevron-forward" size={17}/></Pressable>}
  <View style={h.section}><Text style={h.sectionTitle}>我的事項</Text><Pressable accessibilityRole="button" onPress={onCalendar} style={h.link}><Text style={h.linkText}>查看月曆</Text><Icon name="arrow-forward" size={15}/></Pressable></View>
  <Chips<typeof filter> values={[["today",`今天 ${today.length}`],["todo",`待辦 ${todos.length}`],["review",`待確認 ${review.length}`],["all","全部"]]} value={filter} onChange={v=>{setFilter(v);setQuery('');setLimit(12)}}/>
  {(filter==='all'||source.length>12)&&<Field label="搜尋事項" value={query} onChange={q=>{setQuery(q);setLimit(12)}} placeholder="名稱、地點或內容" max={200}/>}
  {items.slice(0,limit).map(n=>filter==='todo'?<View key={n.id} style={h.todo}><Pressable accessibilityRole="checkbox" accessibilityState={{checked:false}} accessibilityLabel={`完成 ${n.title}`} onPress={()=>onToggle(n)} style={h.check}><Icon name="ellipse-outline" color={p.muted}/></Pressable><Pressable accessibilityRole="button" style={s.flex} onPress={()=>onOpen(n.id)}><Text style={h.eventTitle}>{n.title}</Text><Text style={s.caption}>{n.checklist.length?`${n.checklist.filter(c=>c.done).length}/${n.checklist.length} 項準備事項`:n.category}</Text></Pressable><Icon name="chevron-forward" color={p.muted} size={17}/></View>:<EventCard key={n.id} notice={n} onOpen={onOpen}/>)}
  {!items.length&&<View style={h.empty}><View style={h.emptyIcon}><Icon name={filter==='review'?'checkmark-done-outline':'leaf-outline'} size={28}/></View><Text style={h.emptyTitle}>{query?'找不到符合的事項':filter==='today'?'今天還沒有安排':filter==='review'?'目前沒有需要確認的內容':'目前沒有事項'}</Text><Text style={[s.caption,{textAlign:'center'}]}>{query?'試試其他關鍵字。':'用右上角的 ＋，記下下一件重要的事。'}</Text></View>}
  {items.length>limit&&<Button label={`查看更多（還有 ${items.length-limit} 筆）`} secondary onPress={()=>setLimit(v=>v+20)}/>}
 </View>;
}
const h=StyleSheet.create({headingRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10,marginBottom:16},eyebrow:{fontSize:12,color:p.muted,marginBottom:7,letterSpacing:.6},heading:{fontSize:27,fontWeight:'800',color:p.ink,letterSpacing:-1},add:{width:48,height:48,borderRadius:17,backgroundColor:p.green,justifyContent:'center',alignItems:'center'},hero:{backgroundColor:'#153C34',borderRadius:26,padding:20,marginBottom:14},heroTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},heroLabel:{fontSize:12,color:'#CEDCD4',letterSpacing:1},heroTitle:{fontSize:25,lineHeight:35,fontWeight:'700',color:'#FAF7EF',marginTop:12,marginBottom:14},heroBottom:{flexDirection:'row',alignItems:'center',gap:10},heroMeta:{flex:1,fontSize:12,lineHeight:20,color:'#D1DED7'},heroArrow:{width:34,height:34,borderRadius:17,backgroundColor:'#EBD6B7',justifyContent:'center',alignItems:'center'},quickRow:{flexDirection:'row',gap:12,marginBottom:14},quick:{flex:1,flexDirection:'row',alignItems:'center',gap:8,backgroundColor:'white',padding:12,borderRadius:19,minHeight:68},quickIcon:{width:35,height:38,borderRadius:12,alignItems:'center',justifyContent:'center'},quickText:{flex:1,fontSize:13,fontWeight:'600',color:p.ink},progressCard:{padding:14,backgroundColor:'#ECEFE7',borderRadius:16,marginBottom:12},track:{height:4,borderRadius:2,backgroundColor:'#D7DFD3',marginTop:10,overflow:'hidden'},fill:{height:4,backgroundColor:p.green},setup:{flexDirection:'row',gap:9,alignItems:'center',padding:12},section:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:10},sectionTitle:{fontSize:20,fontWeight:'700',color:p.ink},link:{flexDirection:'row',alignItems:'center',gap:5,minHeight:44},linkText:{color:p.green,fontSize:12,fontWeight:'600'},event:{flexDirection:'row',alignItems:'center',gap:12,backgroundColor:'white',padding:15,borderRadius:20,marginBottom:10},dateBlock:{width:52,minHeight:59,borderRadius:14,alignItems:'center',justifyContent:'center',padding:5},dateNumber:{fontSize:23,fontWeight:'700'},dateMonth:{fontSize:10,fontWeight:'600'},eventTitle:{fontSize:16,fontWeight:'600',color:p.ink,lineHeight:23,marginBottom:3},todo:{flexDirection:'row',alignItems:'center',backgroundColor:'white',borderRadius:18,paddingVertical:12,paddingRight:16,marginBottom:9,gap:8},check:{width:48,minHeight:48,alignItems:'center',justifyContent:'center'},empty:{alignItems:'center',paddingVertical:30,paddingHorizontal:20,backgroundColor:'#EFEFE7',borderRadius:22},emptyIcon:{width:52,height:52,borderRadius:20,backgroundColor:'#E1E7DA',justifyContent:'center',alignItems:'center',marginBottom:14},emptyTitle:{fontSize:16,fontWeight:'600',color:p.ink,marginBottom:6}});
