import React,{useState} from 'react';
import {Pressable,StyleSheet,Text,TextInput,View} from 'react-native';
import type {Notice} from './domain';
import {dayKey,displayDay,displayTime,noticesForDay} from './calendar';
import {Button,Chips,Field,Icon,p,s} from './ui';

const tones={生活:['#E4EFE9','#326753','leaf-outline'],學校:['#EAE6F6','#65568A','school-outline'],帳單:['#F9EBDD','#966034','receipt-outline'],取件:['#E1EDF3','#426B80','cube-outline'],活動:['#FAE4DD','#A45741','sparkles-outline']} as const;

export function EventCard({notice:n,onOpen}:{notice:Notice;onOpen:(id:string)=>void}){
 const [soft,color,icon]=tones[n.category];
 return <Pressable accessibilityRole="button" accessibilityLabel={`${n.title}，查看行程`} onPress={()=>onOpen(n.id)} style={({pressed})=>[h.event,pressed&&{opacity:.72}]}>
  <View style={[h.dateBlock,{backgroundColor:soft}]}>{n.dueAt?<><Text style={[h.dateNumber,{color}]}>{new Date(n.dueAt).getDate()}</Text><Text style={[h.dateMonth,{color}]}>{new Date(n.dueAt).getMonth()+1} 月</Text></>:<Icon name={icon} color={color} size={23}/>}</View>
  <View style={s.flex}><View style={h.eventHeading}><Text numberOfLines={2} style={[h.eventTitle,s.flex]}>{n.title}</Text>{n.needsReview&&<View style={h.reviewBadge}><Text style={h.reviewText}>待確認</Text></View>}</View><Text numberOfLines={1} style={s.caption}>{n.dueAt?n.allDay?'全天':displayTime(new Date(n.dueAt)):'時間待確認'}{n.location?` · ${n.location}`:` · ${n.category}`}</Text></View><Icon name="chevron-forward" size={18} color={p.muted}/>
 </Pressable>;
}

type Filter='today'|'upcoming'|'review'|'all';
export function HomeDashboard({notices,onOpen,onAdd,onQuickAdd,onCapture,onCalendar,onSettings,onRefresh,listenerEnabled,listenerConnected,pendingCount,captureMessage,importing,issue}:{notices:Notice[];onOpen:(id:string)=>void;onAdd:()=>void;onQuickAdd:(text:string)=>void;onCapture:(type:'image'|'text')=>void;onCalendar:()=>void;onSettings:()=>void;onRefresh:()=>void;listenerEnabled:boolean;listenerConnected:boolean;pendingCount:number;captureMessage:string;importing:boolean;issue:string}){
 const[filter,setFilter]=useState<Filter>('today'),[query,setQuery]=useState(''),[limit,setLimit]=useState(12),[quickText,setQuickText]=useState('');
 const now=new Date(),events=notices.filter(n=>!n.done&&n.dueAt),today=noticesForDay(events,dayKey(now)),review=events.filter(n=>n.needsReview);
 const weekEnd=new Date(now.getFullYear(),now.getMonth(),now.getDate()+8).getTime();
 const upcoming=events.filter(n=>!n.needsReview&&Date.parse(n.endAt||n.dueAt!)>=now.getTime()&&Date.parse(n.dueAt!)<weekEnd).sort((a,b)=>Date.parse(a.dueAt!)-Date.parse(b.dueAt!));
 const next=events.filter(n=>!n.needsReview&&(n.allDay?dayKey(n.dueAt!)>=dayKey(now):Date.parse(n.endAt||n.dueAt!)>=now.getTime())).sort((a,b)=>Date.parse(a.dueAt!)-Date.parse(b.dueAt!))[0];
 const source=filter==='today'?today:filter==='upcoming'?upcoming:filter==='review'?review:events;
 const items=source.filter(n=>!query.trim()||`${n.title} ${n.location||''} ${n.source}`.toLowerCase().includes(query.trim().toLowerCase()));
 const selectFilter=(nextFilter:Filter)=>{setFilter(nextFilter);setQuery('');setLimit(12)};
 const submitQuick=()=>{const text=quickText.trim();if(!text)return;setQuickText('');onQuickAdd(text)};
 return <View>
  <View style={h.headingRow}><View><Text style={h.eyebrow}>{displayDay(now)}</Text><Text style={h.heading}>今天，別錯過重要行程</Text></View><Pressable accessibilityRole="button" accessibilityLabel="新增行程" onPress={onAdd} style={h.add}><Icon name="add" color="white" size={26}/></Pressable></View>

  <View style={h.composer}><View style={h.composerIcon}><Icon name="sparkles" color="#7B5538" size={19}/></View><TextInput accessibilityLabel="用一句話新增行程" value={quickText} onChangeText={setQuickText} onSubmitEditing={submitQuick} returnKeyType="done" maxLength={500} placeholder="例如：明晚 7:30 和安玲吃飯" placeholderTextColor="#87918C" style={h.composerInput}/><Pressable accessibilityRole="button" accessibilityLabel="整理這句話" disabled={!quickText.trim()} onPress={submitQuick} style={({pressed})=>[h.composerSend,(!quickText.trim()||pressed)&&{opacity:.45}]}><Icon name="arrow-up" color="white" size={20}/></Pressable></View>

  <Pressable accessibilityRole="button" accessibilityLabel={next?`下一個行程：${next.title}`:'新增第一個行程'} onPress={()=>next?onOpen(next.id):onAdd()} style={h.hero}>
   <View pointerEvents="none" style={h.heroGlow}/><View pointerEvents="none" style={h.heroGlowSmall}/>
   <View style={h.heroTop}><View style={h.heroPill}><View style={h.heroDot}/><Text style={h.heroLabel}>{next?'接下來':'準備就緒'}</Text></View><Icon name={next?'arrow-forward-outline':'sunny-outline'} color="#F0D2AD" size={23}/></View>
   <Text numberOfLines={2} style={h.heroTitle}>{next?next.title:'目前沒有即將到來的行程'}</Text>
   <View style={h.heroBottom}><Text numberOfLines={2} style={h.heroMeta}>{next?`${displayDay(new Date(next.dueAt!))} · ${next.allDay?'全天':displayTime(new Date(next.dueAt!))}${next.location?` · ${next.location}`:''}`:'輸入一句話，快速建立下一個行程'}</Text><View style={h.heroArrow}><Icon name="arrow-forward" color="#153C34" size={19}/></View></View>
  </Pressable>

  <View style={h.metrics}>{([['today','今天',today.length,'today-outline'],['upcoming','7 天內',upcoming.length,'calendar-outline'],['review','待確認',review.length,'alert-circle-outline']] as const).map(([key,label,count,icon])=><Pressable key={key} accessibilityRole="button" accessibilityLabel={`${label} ${count} 個行程`} onPress={()=>selectFilter(key)} style={[h.metric,filter===key&&h.metricActive]}><Icon name={icon} size={18} color={filter===key?p.green:p.muted}/><Text style={h.metricNumber}>{count}</Text><Text style={h.metricLabel}>{label}</Text>{key==='review'&&count>0&&<View style={h.badgeDot}/>}</Pressable>)}</View>

  <View style={h.quickRow}>{([['image','scan-outline','辨識截圖','#F6E5DC'],['text','clipboard-outline','貼上文字','#E9E5F5']] as const).map(([type,icon,title,color])=><Pressable accessibilityRole="button" key={type} onPress={()=>onCapture(type)} style={({pressed})=>[h.quick,pressed&&{opacity:.65}]}><View style={[h.quickIcon,{backgroundColor:color}]}><Icon name={icon} color={p.ink} size={22}/></View><View style={s.flex}><Text style={h.quickText}>{title}</Text><Text style={h.quickHint}>{type==='image'?'找出圖片中的行程':'整理剪貼簿行程'}</Text></View><Icon name="chevron-forward" size={17} color={p.muted}/></Pressable>)}</View>

  {!!issue&&<Text accessibilityLiveRegion="polite" style={s.warning}>{issue}</Text>}
  {!listenerEnabled?<Pressable accessibilityRole="button" onPress={onSettings} style={h.setup}><Icon name="notifications-outline" size={20}/><View style={s.flex}><Text style={h.statusTitle}>開啟自動收件</Text><Text style={s.caption}>從通知中找出有明確時間的行程</Text></View><Icon name="chevron-forward" size={17}/></Pressable>:!listenerConnected?<Pressable accessibilityRole="button" onPress={onSettings} style={h.setup}><Icon name="warning-outline" size={20} color={p.orange}/><View style={s.flex}><Text style={h.statusTitle}>通知服務尚未連線</Text><Text style={s.caption}>點此重新啟動</Text></View><Icon name="chevron-forward" size={17}/></Pressable>:<Pressable accessibilityRole="button" accessibilityLabel="立即整理通知收件匣" disabled={importing} onPress={onRefresh} style={h.captureStatus}><Icon name={importing?'sync-outline':pendingCount?'file-tray-outline':'checkmark-circle-outline'} size={19} color={pendingCount?p.orange:p.green}/><View style={s.flex}><Text style={h.statusTitle}>{importing?'正在辨識行程':pendingCount?`${pendingCount} 則通知等待判斷`:'行程監聽運作中'}</Text><Text accessibilityLiveRegion="polite" numberOfLines={2} style={s.caption}>{importing?'只會保留有明確日期的行程':pendingCount?'點此立即重試':captureMessage||'廣告與一般待辦會直接略過'}</Text></View><Icon name="refresh-outline" size={17} color={p.muted}/></Pressable>}

  <View style={h.section}><View><Text style={h.sectionTitle}>我的行程</Text><Text style={h.sectionHint}>{filter==='today'?'今天的時間表':filter==='upcoming'?'接下來七天的安排':filter==='review'?'需要確認日期或時間':'所有尚未結束的行程'}</Text></View><Pressable accessibilityRole="button" onPress={onCalendar} style={h.link}><Text style={h.linkText}>月曆</Text><Icon name="arrow-forward" size={15}/></Pressable></View>
  <Chips<Filter> values={[["today",`今天 ${today.length}`],["upcoming",`近期 ${upcoming.length}`],["review",`待確認 ${review.length}`],["all","全部"]]} value={filter} onChange={selectFilter}/>
  {(filter==='all'||source.length>12)&&<Field label="搜尋行程" value={query} onChange={q=>{setQuery(q);setLimit(12)}} placeholder="名稱、地點或內容" max={200}/>}
  {items.slice(0,limit).map(n=><EventCard key={n.id} notice={n} onOpen={onOpen}/>)}
  {!items.length&&<View style={h.empty}><View style={h.emptyIcon}><Icon name={filter==='review'?'checkmark-done-outline':filter==='upcoming'?'calendar-clear-outline':'leaf-outline'} size={28}/></View><Text style={h.emptyTitle}>{query?'找不到符合的行程':filter==='today'?'今天沒有安排':filter==='upcoming'?'未來七天目前沒有行程':filter==='review'?'所有時間都確認完了':'目前沒有行程'}</Text><Text style={[s.caption,{textAlign:'center'}]}>{query?'試試其他關鍵字。':'在上方輸入一句話，快速記下下一個行程。'}</Text></View>}
  {items.length>limit&&<Button label={`查看更多（還有 ${items.length-limit} 筆）`} secondary onPress={()=>setLimit(v=>v+20)}/>}
 </View>;
}

const h=StyleSheet.create({
 headingRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10,marginBottom:14},eyebrow:{fontSize:12,color:p.muted,marginBottom:6,letterSpacing:.5},heading:{fontSize:26,lineHeight:34,fontWeight:'800',color:p.ink,letterSpacing:-.8},add:{width:48,height:48,borderRadius:18,backgroundColor:p.green,justifyContent:'center',alignItems:'center',shadowColor:p.green,shadowOpacity:.2,shadowRadius:9,shadowOffset:{width:0,height:4},elevation:3},
 composer:{flexDirection:'row',alignItems:'center',gap:9,backgroundColor:'white',borderWidth:1,borderColor:'#DDE4DE',borderRadius:21,padding:8,marginBottom:13,shadowColor:'#173B34',shadowOpacity:.05,shadowRadius:14,shadowOffset:{width:0,height:5},elevation:1},composerIcon:{width:37,height:37,borderRadius:14,backgroundColor:'#F6E7D7',alignItems:'center',justifyContent:'center'},composerInput:{flex:1,minHeight:44,fontSize:15,color:p.ink,paddingVertical:8,paddingHorizontal:2},composerSend:{width:39,height:39,borderRadius:14,backgroundColor:p.green,alignItems:'center',justifyContent:'center'},
 hero:{position:'relative',overflow:'hidden',backgroundColor:'#153C34',borderRadius:27,padding:20,marginBottom:12,minHeight:177,shadowColor:'#153C34',shadowOpacity:.18,shadowRadius:16,shadowOffset:{width:0,height:8},elevation:3},heroGlow:{position:'absolute',width:180,height:180,borderRadius:90,backgroundColor:'#3A7564',right:-75,top:-65,opacity:.45},heroGlowSmall:{position:'absolute',width:82,height:82,borderRadius:41,backgroundColor:'#D39E68',right:44,bottom:-48,opacity:.22},heroTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},heroPill:{flexDirection:'row',alignItems:'center',gap:7,backgroundColor:'#FFFFFF14',paddingHorizontal:10,paddingVertical:7,borderRadius:99},heroDot:{width:7,height:7,borderRadius:4,backgroundColor:'#F0C996'},heroLabel:{fontSize:11,fontWeight:'700',color:'#D8E5DE',letterSpacing:.8},heroTitle:{fontSize:24,lineHeight:34,fontWeight:'700',color:'#FAF7EF',marginTop:15,marginBottom:13},heroBottom:{flexDirection:'row',alignItems:'center',gap:10},heroMeta:{flex:1,fontSize:12,lineHeight:19,color:'#D1DED7'},heroArrow:{width:35,height:35,borderRadius:18,backgroundColor:'#F0D4AE',justifyContent:'center',alignItems:'center'},
 metrics:{flexDirection:'row',gap:8,marginBottom:12},metric:{position:'relative',flex:1,alignItems:'flex-start',backgroundColor:'white',borderRadius:18,padding:12,borderWidth:1,borderColor:'transparent'},metricActive:{backgroundColor:'#EEF3EB',borderColor:'#D4E1D9'},metricNumber:{fontSize:23,fontWeight:'800',color:p.ink,marginTop:7},metricLabel:{fontSize:11,color:p.muted,marginTop:1},badgeDot:{position:'absolute',right:10,top:10,width:8,height:8,borderRadius:4,backgroundColor:'#D77C57'},
 quickRow:{flexDirection:'row',gap:10,marginBottom:12},quick:{flex:1,flexDirection:'row',alignItems:'center',gap:8,backgroundColor:'white',padding:11,borderRadius:18,minHeight:67},quickIcon:{width:37,height:41,borderRadius:13,alignItems:'center',justifyContent:'center'},quickText:{fontSize:13,fontWeight:'700',color:p.ink},quickHint:{fontSize:10,color:p.muted,marginTop:2},setup:{flexDirection:'row',gap:11,alignItems:'center',padding:13,backgroundColor:'#F2EEE7',borderRadius:16,marginBottom:4},captureStatus:{flexDirection:'row',gap:11,alignItems:'center',padding:13,backgroundColor:'#EDF3EE',borderRadius:16,marginBottom:4},statusTitle:{fontSize:13,fontWeight:'700',color:p.ink},
 section:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:17},sectionTitle:{fontSize:20,fontWeight:'700',color:p.ink},sectionHint:{fontSize:11,color:p.muted,marginTop:3},link:{flexDirection:'row',alignItems:'center',gap:5,minHeight:44,paddingHorizontal:4},linkText:{color:p.green,fontSize:13,fontWeight:'700'},event:{flexDirection:'row',alignItems:'center',gap:12,backgroundColor:'white',padding:14,borderRadius:20,marginBottom:10,borderWidth:1,borderColor:'#EAEBE5',shadowColor:'#173B34',shadowOpacity:.025,shadowRadius:8,shadowOffset:{width:0,height:3},elevation:1},dateBlock:{width:52,minHeight:59,borderRadius:16,alignItems:'center',justifyContent:'center',padding:5},dateNumber:{fontSize:23,fontWeight:'800'},dateMonth:{fontSize:10,fontWeight:'700'},eventHeading:{flexDirection:'row',alignItems:'flex-start',gap:6},eventTitle:{fontSize:16,fontWeight:'600',color:p.ink,lineHeight:23,marginBottom:3},reviewBadge:{backgroundColor:'#FFF0E5',borderRadius:99,paddingHorizontal:7,paddingVertical:3},reviewText:{fontSize:9,fontWeight:'800',color:'#A15C37'},empty:{alignItems:'center',paddingVertical:30,paddingHorizontal:20,backgroundColor:'#EFEFE7',borderRadius:22},emptyIcon:{width:52,height:52,borderRadius:20,backgroundColor:'#E1E7DA',justifyContent:'center',alignItems:'center',marginBottom:14},emptyTitle:{fontSize:16,fontWeight:'700',color:p.ink,marginBottom:6}
});
